services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../../'
        exclude:
            - '../../Tests/'
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'

    App\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Controller\ImportRepositoriesController:
        arguments:
            $demoMode: "%demo_mode%"
        tags: [ 'controller.service_arguments' ]

    App\Controller\WebhookController:
        arguments:
            $webhookSecret: "%app.github.webhook_secret%"
        tags: [ 'controller.service_arguments' ]

    App\Entity\Repository\ProjectRepository:
        class: App\Entity\Repository\ProjectRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ['App\Entity\Project']

    App\Entity\Repository\PackageRepository:
        class: App\Entity\Repository\PackageRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ['App\Entity\Package']

    App\DataFixtures\AppFixtures:
        tags: ['doctrine.fixture.orm']

    App\ProjectImport\ProjectProviderInterface:
        alias: App\ProjectImport\DoctrineProjectProvider

    App\Factory\VcsDriverFactory:
        arguments:
            $githubOAuthToken: "%app.github.token%"

    app.form.type.datalist_type:
        class: App\Form\Type\DatalistType
        tags:
            -  { name: form.type, alias: datalist }