services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../../'
        exclude:
            - '../../Tests/'
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'